#!/usr/bin/env bash

if [ $EUID != 0 ]; then
        echo "this script must be run using sudo"
        echo ""
        echo "usage:"
        echo "sudo ./configserial"
        exit $exit_code
   exit 1
fi

stty -F /dev/ttyUSB0 1000000
